contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
category = "categories"
baseurl = "http://Human-May-Cry.github.io/"
title =  "ハヤテ"
canonifyurls = true
theme = "hugo-uno"

[Params]
cover = "/img/fender1.jpg"
logo = "/img/my_picture.jpeg"